### ISSUE TITLE
Change the text color

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-learns-git#4]
In `app.component.css`, define a new style for headings by adding the code
```css
h1 {
  color: pink;
}
```
Feel free to pick any color or define other style properties.
